spring:
  application:
    name: ProductService
  datasource:
    url: jdbc:postgresql://localhost:5432/Product
    username: postgres
    password: slk@SOFT123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      enabled: false

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
app:
  upload:
  dir: uploads