spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:postgresql://localhost:5432/ECom_Payment
    username: postgres
    password: slk@SOFT123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      enabled: false

server:
  port: 8087

services:
  security: http://localhost:9999
  order: http://localhost:8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
razorpay:
  keyId: rzp_test_SMoFjsYTgnbVXO
  keySecret: SE1uiNimaXsutaXh60syqOXv
