spring:
  application:
    name: SpringSecurityService
  datasource:
    url: jdbc:postgresql://localhost:5432/ECom
    username: postgres
    password: slk@SOFT123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

server:
  port: 9999

springdoc:
  packagesToScan: com.example.demo